//! Golden palette configs: `<name>.palettes.toml` next to each sample image (X1).
//!
//! ```toml
//! [[palette]]
//! size = 3
//! picks = [
//!   { rgba = [210, 120, 40, 255], ink = "Pantone 1595" },
//! ]
//! ```
//!
//! Each pick is a pixel color and the palette entry (by name) it maps to. "Size" is the requested
//! number of distinct inks; a palette may list fewer picks ("up to N").

use std::path::{Path, PathBuf};

use anyhow::{Context, Result, anyhow, bail};
use rekolor_core::{Mapping, Palette, Rgba8, composite_over_white};
use serde::Deserialize;

#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PaletteConfig {
    pub palette: Vec<SizedPalette>,
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SizedPalette {
    pub size: u32,
    pub picks: Vec<ConfigPick>,
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConfigPick {
    pub rgba: [u8; 4],
    pub ink: String,
}

/// `foo/bar.png` → `foo/bar.palettes.toml`.
pub fn config_path(image: &Path) -> PathBuf {
    image.with_file_name(format!("{}.palettes.toml", stem(image)))
}

/// `foo/bar.png`, size 3 → `foo/bar-out-3.png`.
pub fn output_path(image: &Path, size: u32) -> PathBuf {
    image.with_file_name(format!("{}-out-{size}.png", stem(image)))
}

fn stem(path: &Path) -> String {
    path.file_stem()
        .map(|s| s.to_string_lossy().into_owned())
        .unwrap_or_default()
}

impl PaletteConfig {
    pub fn load(path: &Path) -> Result<Self> {
        let text =
            std::fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
        Self::parse(&text).with_context(|| format!("parsing {}", path.display()))
    }

    pub fn parse(text: &str) -> Result<Self> {
        let config: PaletteConfig = toml::from_str(text)?;
        let mut sizes: Vec<u32> = config.palette.iter().map(|p| p.size).collect();
        sizes.sort_unstable();
        if sizes.windows(2).any(|w| w[0] == w[1]) {
            bail!("a palette size appears more than once");
        }
        Ok(config)
    }

    pub fn size(&self, size: u32) -> Result<&SizedPalette> {
        self.palette
            .iter()
            .find(|p| p.size == size)
            .ok_or_else(|| anyhow!("no palette of size {size} in the config"))
    }

    /// Writes the config in the agreed simple format, with a short explanatory header.
    pub fn to_toml(&self, image_name: &str, generated_by: &str) -> String {
        let mut out = format!(
            "# Golden palettes for {image_name}.\n\
             # First version generated by `{generated_by}`. Edit freely: this file is the\n\
             # source of truth for the golden outputs ({}-out-<size>.png).\n",
            image_name
                .rsplit_once('.')
                .map_or(image_name, |(stem, _)| stem)
        );
        for palette in &self.palette {
            out.push_str(&format!(
                "\n[[palette]]\nsize = {}\npicks = [\n",
                palette.size
            ));
            for pick in &palette.picks {
                let [r, g, b, a] = pick.rgba;
                // JSON string escaping is valid TOML basic-string escaping.
                let ink = serde_json::to_string(&pick.ink).expect("strings serialize");
                out.push_str(&format!(
                    "  {{ rgba = [{r}, {g}, {b}, {a}], ink = {ink} }},\n"
                ));
            }
            out.push_str("]\n");
        }
        out
    }
}

impl SizedPalette {
    /// The mappings for recoloring: each pick's color as the matcher sees it (composited over
    /// white, as for an interactive pick) → the named palette entry's color.
    pub fn mappings(&self, palette: &Palette) -> Result<Vec<Mapping>> {
        self.picks
            .iter()
            .map(|pick| {
                let entry = palette
                    .entries()
                    .iter()
                    .find(|e| e.name == pick.ink)
                    .ok_or_else(|| anyhow!("ink {:?} is not in the palette", pick.ink))?;
                Ok(Mapping {
                    source: composite_over_white(Rgba8::from(pick.rgba)),
                    ink: entry.rgb,
                })
            })
            .collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rekolor_core::{PaletteEntry, Rgb8};

    fn sample() -> PaletteConfig {
        PaletteConfig {
            palette: vec![
                SizedPalette {
                    size: 3,
                    picks: vec![
                        ConfigPick {
                            rgba: [210, 120, 40, 255],
                            ink: "Pantone 1595".into(),
                        },
                        ConfigPick {
                            rgba: [0, 0, 0, 0],
                            ink: "Pure White (non-palette)".into(),
                        },
                    ],
                },
                SizedPalette {
                    size: 7,
                    picks: vec![],
                },
            ],
        }
    }

    #[test]
    fn writes_the_simple_format_and_reads_it_back() {
        let text = sample().to_toml("04-tiger.png", "rekolor palettes generate");
        assert!(text.contains("# Golden palettes for 04-tiger.png."));
        assert!(text.contains("04-tiger-out-<size>.png"));
        assert!(text.contains("  { rgba = [210, 120, 40, 255], ink = \"Pantone 1595\" },\n"));
        assert_eq!(PaletteConfig::parse(&text).unwrap(), sample());
    }

    #[test]
    fn rejects_unknown_fields_and_duplicate_sizes() {
        assert!(PaletteConfig::parse("[[palette]]\nsize = 3\npicks = []\nextra = 1\n").is_err());
        assert!(
            PaletteConfig::parse(
                "[[palette]]\nsize = 3\npicks = []\n[[palette]]\nsize = 3\npicks = []\n"
            )
            .is_err()
        );
    }

    #[test]
    fn mappings_composite_the_pick_and_look_up_the_ink() {
        let palette = Palette::new(vec![
            PaletteEntry::new("Pure White (non-palette)", Rgb8::new(255, 255, 255)),
            PaletteEntry::new("Pantone 1595", Rgb8::new(209, 91, 5)),
        ])
        .unwrap();
        let config = sample();
        let mappings = config.size(3).unwrap().mappings(&palette).unwrap();
        assert_eq!(mappings[0].source, Rgb8::new(210, 120, 40));
        assert_eq!(mappings[0].ink, Rgb8::new(209, 91, 5));
        // A transparent pick is matched as white, like an interactive pick.
        assert_eq!(mappings[1].source, Rgb8::new(255, 255, 255));

        assert!(config.size(16).is_err());
        let unknown = SizedPalette {
            size: 1,
            picks: vec![ConfigPick {
                rgba: [0, 0, 0, 255],
                ink: "Nope".into(),
            }],
        };
        assert!(unknown.mappings(&palette).is_err());
    }

    #[test]
    fn paths_sit_next_to_the_image() {
        let image = Path::new("samples/good-looking/04-tiger.png");
        assert_eq!(
            config_path(image),
            Path::new("samples/good-looking/04-tiger.palettes.toml")
        );
        assert_eq!(
            output_path(image, 16),
            Path::new("samples/good-looking/04-tiger-out-16.png")
        );
    }
}
