//! Golden palette configs on disk: `<name>.palettes.toml` next to each sample image (X1).
//!
//! The format, its validation and the conversion to mappings live in `rekolor-config` (shared with
//! the web app, W10 v); this module adds the CLI's file names, reading, and the golden-file header.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
pub use rekolor_config::{
    ConfigError, ConfigPick, DEFAULT_UNPRINTED_DELTA_E, PaletteConfig, SizedPalette, Unprinted,
};

/// `foo/bar.png` → `foo/bar.palettes.toml`.
pub fn config_path(image: &Path) -> PathBuf {
    image.with_file_name(format!("{}.palettes.toml", stem(image)))
}

/// `foo/bar.png`, size 3 → `foo/bar-out-3.png`.
pub fn output_path(image: &Path, size: u32) -> PathBuf {
    image.with_file_name(format!("{}-out-{size}.png", stem(image)))
}

fn stem(path: &Path) -> String {
    path.file_stem()
        .map(|s| s.to_string_lossy().into_owned())
        .unwrap_or_default()
}

/// Reads and validates a config file.
pub fn load(path: &Path) -> Result<PaletteConfig> {
    let text =
        std::fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    PaletteConfig::parse(&text).with_context(|| format!("parsing {}", path.display()))
}

/// The config as written next to a golden image, with its explanatory header.
pub fn golden_toml(config: &PaletteConfig, image_name: &str, generated_by: &str) -> String {
    let stem = image_name
        .rsplit_once('.')
        .map_or(image_name, |(stem, _)| stem);
    config.to_toml(&[
        &format!("Golden palettes for {image_name}."),
        &format!("First version generated by `{generated_by}`. Edit freely: this file is the"),
        &format!("source of truth for the golden outputs ({stem}-out-<size>.png)."),
    ])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn golden_header_is_unchanged() {
        let config = PaletteConfig {
            material: [255, 255, 255],
            unprinted: vec![],
            palette: vec![SizedPalette {
                size: 3,
                picks: vec![ConfigPick {
                    rgba: [210, 120, 40, 255],
                    ink: "Pantone 1595".into(),
                }],
            }],
        };
        assert_eq!(
            golden_toml(&config, "04-tiger.png", "rekolor palettes generate"),
            "# Golden palettes for 04-tiger.png.\n\
             # First version generated by `rekolor palettes generate`. Edit freely: this file is the\n\
             # source of truth for the golden outputs (04-tiger-out-<size>.png).\n\
             \nmaterial = [255, 255, 255]\nunprinted = []\n\
             \n[[palette]]\nsize = 3\npicks = [\n  { rgba = [210, 120, 40, 255], ink = \"Pantone 1595\" },\n]\n"
        );
    }

    #[test]
    fn paths_sit_next_to_the_image() {
        let image = Path::new("samples/good-looking/04-tiger.png");
        assert_eq!(
            config_path(image),
            Path::new("samples/good-looking/04-tiger.palettes.toml")
        );
        assert_eq!(
            output_path(image, 16),
            Path::new("samples/good-looking/04-tiger-out-16.png")
        );
    }
}
