// Node-only test helper: initializes the WASM package from disk (no fetch) and reads the palette.

import { readFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import init from 'rekolor-wasm';

// Load the module once for all tests: `??=` assigns only when `ready` is still `undefined`.
// `createRequire(...).resolve` finds the `.wasm` file inside the installed package, and `init`
// (generated by wasm-bindgen) compiles it.
let ready: Promise<unknown> | undefined;

export function loadWasm(): Promise<unknown> {
  ready ??= readFile(
    createRequire(import.meta.url).resolve('rekolor-wasm/rekolor_wasm_bg.wasm'),
  ).then((bytes) => init({ module_or_path: bytes }));
  return ready;
}

export const pantoneJson = (): Promise<string> =>
  readFile(new URL('../../../palettes/pantone.json', import.meta.url), 'utf8');
