// Loads the `rekolor-wasm` package (built with `wasm-pack --target web`) the way an app would,
// except that the `.wasm` bytes come from disk instead of `fetch`.

import { readFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import init, { type Outcome } from 'rekolor-wasm';

// `Promise<unknown> | undefined` is a union type: either a pending result or nothing yet.
let ready: Promise<unknown> | undefined;

export function loadWasm(): Promise<unknown> {
  // Load the module only once, however many test files call this: `??=` assigns only when `ready`
  // is still `undefined`. `createRequire(...).resolve` finds the `.wasm` file inside the installed
  // package; `init` (generated by wasm-bindgen) compiles the bytes and prepares the exports.
  ready ??= readFile(
    createRequire(import.meta.url).resolve('rekolor-wasm/rekolor_wasm_bg.wasm'),
  ).then((bytes) => init({ module_or_path: bytes }));
  return ready;
}

// `<T>` makes the function generic: `unwrap(Outcome<Pick>)` returns a `Pick`. After the
// `status === 'error'` check, TypeScript knows the outcome is the `ok` variant, so `outcome.value`
// is allowed (this is called narrowing).
/** The value of an `ok` outcome; fails the test with the error otherwise. */
export function unwrap<T>(outcome: Outcome<T>): T {
  if (outcome.status === 'error') {
    throw new Error(`expected ok, got ${outcome.error.kind}: ${outcome.error.message}`);
  }
  return outcome.value;
}
